version: '3.8'

services:
  app:
    build: .
    container_name: project-a-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - default

networks:
  default:
    external: true
    name: mynetwork
