services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: newsdb
      MYSQL_USER: newsuser
      MYSQL_PASSWORD: newspass
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"

  scraper:
    build:
      context: .
      dockerfile: scraper/Dockerfile
    depends_on:
      - kafka

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      - kafka
      - mysql
